runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets/css.*
  static_dir: assets/css

- url: /assets/js.*
  static_dir: assets/js

- url: /assets/img.*
  static_dir: assets/img

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
